enum Error {
  unknown,

  deviceError,
  noDeviceResponse,
  unexpectedDeviceResponse,
  incorrectDeviceResponse,

  networkError,
  unexpectedNetworkResponse,
  incorrectNetworkFile,

  incorrectMessageSize,
  incorrectMessageHeader,
  incorrectFirmwareSize,
  internalStorageError,
  uploadDisabled,
  uploadRunning,
  uploadStopped,
  installRunning,
  bufferDisabled,
  bufferOverflow,
  compressionNotSupported,
  incorrectCompression,
  incorrectCompressedSize,
  incorrectCompressionChecksum,
  incorrectCompressionParam,
  incorrectCompressionEnd,
  checksumNotSupported,
  incorrectChecksum,
  signatureNotSupported,
  incorrectSignature,
  incorrectSignatureSize,
  pinNotSupported,
  pinChangeError,
}
